"use client"
import { useEffect, useRef, useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { quoteAction } from "@/app/editor/quotes/actions"
import { quoteLabels, quoteStatus, type QuoteSnapshot, type QuoteVersion } from "@/lib/quotes/types"
import { calculateBookingFinancials, formatMinorUnits, type InvoiceParty } from "@/lib/booking/pricing"
import { useEditorLayout } from "@/components/editor/editor-layout-context"
import { toast } from "sonner"

export function QuoteEditor({quote,request,versions,initial,deliveries,services,entries}:{quote:{id:string;number:number;request_id:string};request:{name:string;email:string};versions:QuoteVersion[];initial:QuoteSnapshot;deliveries:{version_id:string;status:string;created_at:string}[];services:{id:string;title:string}[];entries:{id:string;status:string;start_at:string}[]}) {
  const draft=versions.find(v=>v.status==="draft")
  const original=draft?.snapshot?.title?draft.snapshot:initial
  const seed={...original,customer:{...original.customer,email:request.email}}
  const [snapshot,setSnapshot]=useState<QuoteSnapshot>({...seed,lines:seed.lines.length?seed.lines:[{id:crypto.randomUUID(),description:seed.title,quantity_milli:1000,unit_price_minor:0,discount_minor:0,vat_rate_basis_points:2100,subtotal_minor:0,vat_minor:0,total_minor:0}]})
  const [until,setUntil]=useState(draft?.valid_until?.slice(0,10)||new Date(Date.now()+30*86400000).toISOString().slice(0,10))
  const [notice,setNotice]=useState(""),[message,setMessage]=useState(""),[email,setEmail]=useState(request.email),[pending,start]=useTransition()
  const [serviceId,setServiceId]=useState(services[0]?.id||""),[startAt,setStartAt]=useState(""),[endAt,setEndAt]=useState("")
  const router=useRouter()
  const { registerNavigationGuard } = useEditorLayout()
  const formState = JSON.stringify({ snapshot: draft ? snapshot : null, until: draft ? until : null, email, message, serviceId, startAt, endAt })
  const initialFormState = useRef(formState)
  const hasUnsavedChanges = formState !== initialFormState.current
  useEffect(() => registerNavigationGuard(() => {
    if (pending) {
      toast.info("Wacht tot de offerteactie is afgerond.")
      return false
    }
    return !hasUnsavedChanges || window.confirm("U heeft niet-opgeslagen wijzigingen in deze offerte. De pagina verlaten en deze wijzigingen verliezen?")
  }), [registerNavigationGuard, pending, hasUnsavedChanges])
  function run(input:Parameters<typeof quoteAction>[0],success="Opgeslagen.") {start(async()=>{setNotice("");const result=await quoteAction(input);if(result.success){setNotice(success);if("href" in result&&result.href)router.push(result.href);else router.refresh()}else setNotice(result.error)})}
  let total:string
  try {total=formatMinorUnits(calculateBookingFinancials(snapshot.lines).totalMinor)}catch{total="Controleer de bedragen"}
  const partyFields: Array<[keyof InvoiceParty,string]>=[["address_line1","Adres"],["postal_code","Postcode"],["city","Plaats"],["country_code","Landcode"],["email","E-mailadres"]]
  return <div className="min-w-0 space-y-5">
    <section className="rounded-xl border bg-card p-4"><h2 className="text-xl font-semibold">Offerte O-{quote.number}</h2><p className="text-sm text-muted-foreground">{request.name} · {request.email}</p><p role="status" className="my-3 text-sm">{notice}</p>
      <div className="flex flex-wrap gap-2"><Button variant="outline" disabled={pending} onClick={()=>run({action:"link",id:quote.id},"Klantlink verstuurd.")}>Klantpagina versturen</Button><Button variant="outline" disabled={pending} onClick={()=>{if(window.confirm("Alle bestaande klantlinks en sessies voor dit dossier intrekken?"))run({action:"revoke",id:quote.id},"Klanttoegang ingetrokken.")}}>Klanttoegang intrekken</Button><Button variant="outline" asChild><a href={`/editor/requests?request=${quote.request_id}`}>Aanvraag openen</a></Button></div>
      <details className="mt-3"><summary className="cursor-pointer text-sm">Contactadres corrigeren</summary><p className="my-2 text-sm text-muted-foreground">Bestaande klantlinks worden ingetrokken. Aangeboden documenten blijven ongewijzigd; maak zo nodig een nieuwe offerteversie.</p><label className="text-sm">E-mailadres<Input type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><Button className="mt-2" variant="outline" disabled={pending} onClick={()=>run({action:"contact",id:quote.id,email},"Contactadres gewijzigd. Verstuur een nieuwe klantlink.")}>Contactadres opslaan</Button></details>
    </section>
    {draft?<section className="space-y-4 rounded-xl border bg-card p-4"><h3 className="font-semibold">Concept · versie {draft.version}</h3>
      <label className="block text-sm">Titel<Input value={snapshot.title} maxLength={200} onChange={e=>setSnapshot({...snapshot,title:e.target.value})}/></label>
      <div className="grid gap-4 md:grid-cols-2">{(["seller","customer"] as const).map(side=><fieldset key={side} className="space-y-2 rounded-lg border p-3"><legend className="px-1 font-medium">{side==="seller"?"Uw bedrijf":"Klant"}</legend><label className="block text-sm">Naam<Input value={(side==="seller"?snapshot.seller.legal_name:snapshot.customer.name)||""} onChange={e=>setSnapshot({...snapshot,[side]:{...snapshot[side],[side==="seller"?"legal_name":"name"]:e.target.value}})}/></label>{partyFields.map(([field,label])=><label key={field} className="block text-sm">{label}<Input value={snapshot[side][field]||""} disabled={side==="customer"&&field==="email"} onChange={e=>setSnapshot({...snapshot,[side]:{...snapshot[side],[field]:e.target.value}})}/></label>)}{side==="seller"?([['vat_id','Btw-nummer'],['kvk_number','KvK-nummer'],['iban','IBAN']] as const).map(([field,label])=><label key={field} className="block text-sm">{label}<Input value={snapshot.seller[field]||""} onChange={e=>setSnapshot({...snapshot,seller:{...snapshot.seller,[field]:e.target.value}})}/></label>):null}</fieldset>)}</div>
      <fieldset className="space-y-3"><legend className="font-medium">Offerteonderdelen</legend>{snapshot.lines.map((line,index)=><div key={line.id} className="space-y-2 rounded-lg border p-3"><label className="block text-sm">Omschrijving<Input value={line.description} maxLength={200} onChange={e=>setSnapshot({...snapshot,lines:snapshot.lines.map((item,i)=>i===index?{...item,description:e.target.value}:item)})}/></label><div className="grid grid-cols-2 gap-2 lg:grid-cols-4">{([{field:"quantity_milli",label:"Aantal",factor:1000},{field:"unit_price_minor",label:"Prijs excl. btw (€)",factor:100},{field:"discount_minor",label:"Korting (€)",factor:100},{field:"vat_rate_basis_points",label:"Btw (%)",factor:100}] as const).map(({field,label,factor})=><label key={field} className="text-sm">{label}<Input type="number" min="0" step={field==="quantity_milli"?"0.001":"0.01"} value={line[field]/factor} onChange={e=>setSnapshot({...snapshot,lines:snapshot.lines.map((item,i)=>i===index?{...item,[field]:Math.round(Number(e.target.value)*factor)}:item)})}/></label>)}</div><Button variant="ghost" size="sm" disabled={snapshot.lines.length===1} onClick={()=>setSnapshot({...snapshot,lines:snapshot.lines.filter((_,i)=>i!==index)})}>Regel verwijderen</Button></div>)}<Button variant="outline" disabled={snapshot.lines.length>=100} onClick={()=>setSnapshot({...snapshot,lines:[...snapshot.lines,{id:crypto.randomUUID(),description:"",quantity_milli:1000,unit_price_minor:0,discount_minor:0,vat_rate_basis_points:2100,subtotal_minor:0,vat_minor:0,total_minor:0}]})}>Regel toevoegen</Button></fieldset>
      <p className="text-lg font-semibold">Totaal incl. btw: {total}</p><label className="block text-sm">Voorwaarden<Textarea rows={5} maxLength={8000} value={snapshot.terms} onChange={e=>setSnapshot({...snapshot,terms:e.target.value})}/></label><label className="block text-sm">Geldig tot en met (UTC)<Input type="date" value={until} onChange={e=>setUntil(e.target.value)}/></label>
      <div className="flex flex-wrap gap-2"><Button disabled={pending} onClick={()=>run({action:"save",id:draft.id,revision:draft.revision,snapshot,until:`${until}T23:59:59.000Z`})}>Concept opslaan</Button><Button variant="outline" asChild><a target="_blank" rel="noreferrer" href={`/api/quotes/${draft.id}/pdf`}>Opgeslagen concept bekijken</a></Button><Button variant="outline" disabled={pending||!draft.valid_until} onClick={()=>{if(window.confirm("De opgeslagen versie definitief aanbieden op de klantpagina? Controleer eerst de PDF. Versturen per e-mail is een aparte actie."))run({action:"offer",id:draft.id,revision:draft.revision},"Offerte aangeboden. U kunt deze nu e-mailen.")}}>Opgeslagen versie aanbieden</Button></div>
    </section>:<Button disabled={pending} onClick={()=>{if(window.confirm("Een nieuwe versie voorbereiden? Bestaande akkoorden en afspraken blijven behouden."))run({action:"revise",requestId:quote.request_id})}}>Nieuwe versie maken</Button>}
    <section className="space-y-3 rounded-xl border bg-card p-4"><h3 className="font-semibold">Aangeboden versies en klantreacties</h3>{versions.filter(v=>v.status!=="draft").map(v=><article key={v.id} className="rounded-lg border p-3"><h4 className="font-medium">Versie {v.version} · {quoteLabels[quoteStatus(v)]} · {formatMinorUnits(v.snapshot.totalMinor)}</h4>{v.decided_at?<p className="text-sm">Reactie van {v.decision_name} op {new Date(v.decided_at).toLocaleString("nl-NL")}: {v.decision_note}</p>:null}<p className="text-sm text-muted-foreground">E-mail: {{sent:"Verstuurd",failed:"Verzending mislukt of onzeker; controleer voor opnieuw versturen",sending:"Wordt verstuurd"}[deliveries.find(d=>d.version_id===v.id)?.status||""]||"Nog niet verstuurd"}</p><div className="mt-3 flex flex-wrap gap-2"><Button variant="outline" asChild><a href={`/api/quotes/${v.id}/pdf`}>PDF</a></Button>{quoteStatus(v)==="offered"?<><Button disabled={pending} onClick={()=>run({action:"email",id:v.id},"Offerte verstuurd.")}>Offerte e-mailen</Button><Button variant="outline" disabled={pending} onClick={()=>{if(window.confirm("Deze offerte intrekken? De bestaande afspraak blijft staan."))run({action:"withdraw",id:v.id,revision:v.revision})}}>Intrekken</Button></>:null}{v.status==="accepted"?<Button disabled={pending} onClick={()=>run({action:"invoice",id:v.id})}>Conceptfactuur maken</Button>:null}</div>{v.status==="accepted"?<p className="mt-2 text-sm">Controleer de planning. Akkoord bevestigt geen nieuw tijdslot. Factureren kan zodra de gekoppelde afspraak bevestigd is.</p>:null}</article>)}</section>
    <section className="space-y-3 rounded-xl border bg-card p-4"><h3 className="font-semibold">Planning</h3>{entries.length?entries.map(e=><a key={e.id} className="block underline" href={`/editor/calendar?booking=${e.id}`}>Gekoppelde afspraak openen · {new Date(e.start_at).toLocaleString("nl-NL")}</a>):versions.some(v=>v.status==="accepted")?<><p className="text-sm">Plan een tijdvak binnen de ingestelde beschikbaarheid van de dienst. Tijden hieronder zijn in de tijdzone van uw browser. De server controleert beschikbaarheid en capaciteit.</p><label className="block text-sm">Dienst<select className="mt-1 block h-11 w-full rounded-md border bg-background px-3" value={serviceId} onChange={e=>setServiceId(e.target.value)}>{services.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="block text-sm">Begin<Input type="datetime-local" value={startAt} onChange={e=>setStartAt(e.target.value)}/></label><label className="block text-sm">Einde<Input type="datetime-local" value={endAt} onChange={e=>setEndAt(e.target.value)}/></label></div><Button disabled={pending||!serviceId||!startAt||!endAt} onClick={()=>{if(window.confirm("Deze afspraak na beschikbaarheidscontrole bevestigen?"))run({action:"schedule",id:quote.id,serviceId,startAt:new Date(startAt).toISOString(),endAt:new Date(endAt).toISOString()})}}>Controleren en inplannen</Button></>:<p className="text-sm text-muted-foreground">Na akkoord kunt u hier een beschikbare afspraak inplannen.</p>}</section>    <section className="space-y-3 rounded-xl border bg-card p-4"><h3 className="font-semibold">Bericht op klantpagina</h3><p className="text-sm text-muted-foreground">Dit bericht wordt gedeeld met de klant. Interne notities blijven in Aanvragen.</p><Textarea aria-label="Bericht voor klant" value={message} maxLength={8000} onChange={e=>setMessage(e.target.value)}/><Button disabled={pending||!message.trim()} onClick={()=>run({action:"message",id:quote.id,message,key:crypto.randomUUID()},"Bericht op klantpagina geplaatst.")}>Bericht delen</Button></section>
  </div>
}
