import { PDFDocument, StandardFonts, rgb } from "pdf-lib"
import type { QuoteSnapshot } from "./types"
import { portalCopy, quoteDocumentCopy } from "./i18n"

// The exact generated bytes are stored atomically with the offered version.
export async function createQuotePdf(snapshot: QuoteSnapshot, number: string, until: string) {
  const copy=portalCopy(snapshot.locale)
  const labels=quoteDocumentCopy(snapshot.locale)
  const pdf = await PDFDocument.create()
  const font = await pdf.embedFont(StandardFonts.Helvetica)
  let page = pdf.addPage([595, 842]), y = 790
  const clean = (s: string) => s.replace(/[^\x20-\x7e\xa0-\xff]/g, " ")
  function line(text: string, size = 11) {
    const words = clean(text).split(/\s+/)
    let row = ""
    const draw = () => {
      if (y < 55) { page = pdf.addPage([595, 842]); y = 790 }
      page.drawText(row, { x: 48, y, size, font, color: rgb(0.08, 0.18, 0.16) }); y -= size + 7
    }
    for (const word of words) {
      let remaining=word
      // Measure glyph widths: a fixed character count overflows for wide letters.
      while(font.widthOfTextAtSize(remaining,size)>495) {
        if(row){draw();row=""}
        let cut=remaining.length-1
        while(cut>1&&font.widthOfTextAtSize(remaining.slice(0,cut),size)>495)cut--
        row=remaining.slice(0,cut);draw();row="";remaining=remaining.slice(cut)
      }
      if (row && font.widthOfTextAtSize(`${row} ${remaining}`, size) > 495) { draw(); row = remaining }
      else row = `${row} ${remaining}`.trim()
    }
    draw()
  }
  line(`${copy.quote.toUpperCase()} ${number}`, 22)
  line(snapshot.title, 15)
  line(snapshot.seller.legal_name || "")
  line([snapshot.seller.address_line1, snapshot.seller.postal_code, snapshot.seller.city].join(" "))
  line(`${snapshot.customer.name || ""} (${snapshot.customer.email || ""})`)
  line([snapshot.customer.address_line1, snapshot.customer.postal_code, snapshot.customer.city].join(" "))
  line(`${copy.valid}: ${new Date(until).toISOString().slice(0, 10)}`)
  const money = (n: number) => `EUR ${(n / 100).toFixed(2)}`
  for (const item of snapshot.lines) {
    line(item.description, 12)
    line(`${item.quantity_milli / 1000} x ${money(item.unit_price_minor)} | ${labels.discount} ${money(item.discount_minor)} | ${labels.vat} ${item.vat_rate_basis_points / 100}% | ${money(item.total_minor)}`)
  }
  line(`${labels.subtotal}: ${money(snapshot.subtotalMinor)}`)
  line(`${labels.vat}: ${money(snapshot.vatTotalMinor)}`)
  line(`${copy.total}: ${money(snapshot.totalMinor)}`, 16)
  line(labels.terms, 14)
  for (const paragraph of snapshot.terms.split("\n")) line(paragraph)
  line(copy.statement)
  return pdf.save()
}
