// Editor-only search metadata. Generated by scripts/vendor-section-icons.mjs.
export const SECTION_ICON_CATALOGUE = [
  {
    "id": "tabler:bed",
    "label": "Bed",
    "category": "Verblijf",
    "keywords": "bed"
  },
  {
    "id": "tabler:bed-flat",
    "label": "Slaapkamer",
    "category": "Verblijf",
    "keywords": "bed flat"
  },
  {
    "id": "tabler:home",
    "label": "Huis",
    "category": "Verblijf",
    "keywords": "home"
  },
  {
    "id": "tabler:building-cottage",
    "label": "Vakantiehuis",
    "category": "Verblijf",
    "keywords": "building cottage"
  },
  {
    "id": "tabler:building-estate",
    "label": "Landgoed",
    "category": "Verblijf",
    "keywords": "building estate"
  },
  {
    "id": "tabler:building-skyscraper",
    "label": "Hotel",
    "category": "Verblijf",
    "keywords": "building skyscraper"
  },
  {
    "id": "tabler:key",
    "label": "Sleutel",
    "category": "Verblijf",
    "keywords": "key"
  },
  {
    "id": "tabler:door",
    "label": "Deur",
    "category": "Verblijf",
    "keywords": "door"
  },
  {
    "id": "tabler:door-enter",
    "label": "Inchecken",
    "category": "Verblijf",
    "keywords": "door enter"
  },
  {
    "id": "tabler:door-exit",
    "label": "Uitchecken",
    "category": "Verblijf",
    "keywords": "door exit"
  },
  {
    "id": "tabler:armchair",
    "label": "Fauteuil",
    "category": "Verblijf",
    "keywords": "armchair"
  },
  {
    "id": "tabler:sofa",
    "label": "Bank",
    "category": "Verblijf",
    "keywords": "sofa"
  },
  {
    "id": "tabler:lamp",
    "label": "Lamp",
    "category": "Verblijf",
    "keywords": "lamp"
  },
  {
    "id": "tabler:air-conditioning",
    "label": "Airconditioning",
    "category": "Verblijf",
    "keywords": "air conditioning"
  },
  {
    "id": "tabler:temperature",
    "label": "Temperatuur",
    "category": "Verblijf",
    "keywords": "temperature"
  },
  {
    "id": "tabler:thermometer",
    "label": "Thermometer",
    "category": "Verblijf",
    "keywords": "thermometer"
  },
  {
    "id": "tabler:flame",
    "label": "Verwarming",
    "category": "Verblijf",
    "keywords": "flame"
  },
  {
    "id": "tabler:snowflake",
    "label": "Koeling",
    "category": "Verblijf",
    "keywords": "snowflake"
  },
  {
    "id": "tabler:bath",
    "label": "Bad",
    "category": "Verblijf",
    "keywords": "bath"
  },
  {
    "id": "tabler:droplets",
    "label": "Water douche",
    "category": "Verblijf",
    "keywords": "droplets"
  },
  {
    "id": "tabler:toilet-paper",
    "label": "Toilet",
    "category": "Verblijf",
    "keywords": "toilet paper"
  },
  {
    "id": "tabler:wash-machine",
    "label": "Wasmachine",
    "category": "Verblijf",
    "keywords": "wash machine"
  },
  {
    "id": "tabler:hanger",
    "label": "Kledinghanger",
    "category": "Verblijf",
    "keywords": "hanger"
  },
  {
    "id": "tabler:ironing",
    "label": "Strijkijzer",
    "category": "Verblijf",
    "keywords": "ironing"
  },
  {
    "id": "tabler:lock",
    "label": "Slot",
    "category": "Verblijf",
    "keywords": "lock"
  },
  {
    "id": "tabler:shield-lock",
    "label": "Kluis",
    "category": "Verblijf",
    "keywords": "shield lock"
  },
  {
    "id": "tabler:luggage",
    "label": "Bagage",
    "category": "Verblijf",
    "keywords": "luggage"
  },
  {
    "id": "tabler:alarm",
    "label": "Wekker",
    "category": "Verblijf",
    "keywords": "alarm"
  },
  {
    "id": "tabler:moon",
    "label": "Nacht",
    "category": "Verblijf",
    "keywords": "moon"
  },
  {
    "id": "tabler:sun",
    "label": "Zon",
    "category": "Verblijf",
    "keywords": "sun"
  },
  {
    "id": "tabler:wifi",
    "label": "Wifi internet draadloos",
    "category": "Faciliteiten",
    "keywords": "wifi"
  },
  {
    "id": "tabler:wifi-off",
    "label": "Geen wifi",
    "category": "Faciliteiten",
    "keywords": "wifi off"
  },
  {
    "id": "tabler:parking",
    "label": "Parkeren",
    "category": "Faciliteiten",
    "keywords": "parking"
  },
  {
    "id": "tabler:car",
    "label": "Auto",
    "category": "Faciliteiten",
    "keywords": "car"
  },
  {
    "id": "tabler:charging-pile",
    "label": "Laadpaal elektrisch",
    "category": "Faciliteiten",
    "keywords": "charging pile"
  },
  {
    "id": "tabler:bike",
    "label": "Fiets",
    "category": "Faciliteiten",
    "keywords": "bike"
  },
  {
    "id": "tabler:motorbike",
    "label": "Motor",
    "category": "Faciliteiten",
    "keywords": "motorbike"
  },
  {
    "id": "tabler:bus",
    "label": "Bus",
    "category": "Faciliteiten",
    "keywords": "bus"
  },
  {
    "id": "tabler:train",
    "label": "Trein",
    "category": "Faciliteiten",
    "keywords": "train"
  },
  {
    "id": "tabler:plane",
    "label": "Vliegtuig",
    "category": "Faciliteiten",
    "keywords": "plane"
  },
  {
    "id": "tabler:walk",
    "label": "Wandelen",
    "category": "Faciliteiten",
    "keywords": "walk"
  },
  {
    "id": "tabler:wheelchair",
    "label": "Rolstoel toegankelijk",
    "category": "Faciliteiten",
    "keywords": "wheelchair"
  },
  {
    "id": "tabler:accessible",
    "label": "Toegankelijkheid",
    "category": "Faciliteiten",
    "keywords": "accessible"
  },
  {
    "id": "tabler:baby-carriage",
    "label": "Kinderwagen",
    "category": "Faciliteiten",
    "keywords": "baby carriage"
  },
  {
    "id": "tabler:baby-bottle",
    "label": "Baby",
    "category": "Faciliteiten",
    "keywords": "baby bottle"
  },
  {
    "id": "tabler:paw",
    "label": "Huisdieren",
    "category": "Faciliteiten",
    "keywords": "paw"
  },
  {
    "id": "tabler:dog",
    "label": "Hond",
    "category": "Faciliteiten",
    "keywords": "dog"
  },
  {
    "id": "tabler:cat",
    "label": "Kat",
    "category": "Faciliteiten",
    "keywords": "cat"
  },
  {
    "id": "tabler:smoking-no",
    "label": "Rookvrij",
    "category": "Faciliteiten",
    "keywords": "smoking no"
  },
  {
    "id": "tabler:smoking",
    "label": "Roken",
    "category": "Faciliteiten",
    "keywords": "smoking"
  },
  {
    "id": "tabler:swimming",
    "label": "Zwembad",
    "category": "Faciliteiten",
    "keywords": "swimming"
  },
  {
    "id": "tabler:pool",
    "label": "Buitenzwembad",
    "category": "Faciliteiten",
    "keywords": "pool"
  },
  {
    "id": "tabler:barbell",
    "label": "Fitness",
    "category": "Faciliteiten",
    "keywords": "barbell"
  },
  {
    "id": "tabler:massage",
    "label": "Massage",
    "category": "Faciliteiten",
    "keywords": "massage"
  },
  {
    "id": "tabler:beach",
    "label": "Strand",
    "category": "Faciliteiten",
    "keywords": "beach"
  },
  {
    "id": "tabler:mountain",
    "label": "Bergen",
    "category": "Faciliteiten",
    "keywords": "mountain"
  },
  {
    "id": "tabler:trees",
    "label": "Bos",
    "category": "Faciliteiten",
    "keywords": "trees"
  },
  {
    "id": "tabler:tree",
    "label": "Tuin boom",
    "category": "Faciliteiten",
    "keywords": "tree"
  },
  {
    "id": "tabler:flower",
    "label": "Bloemen",
    "category": "Faciliteiten",
    "keywords": "flower"
  },
  {
    "id": "tabler:leaf",
    "label": "Groen duurzaam",
    "category": "Faciliteiten",
    "keywords": "leaf"
  },
  {
    "id": "tabler:plant",
    "label": "Plant",
    "category": "Faciliteiten",
    "keywords": "plant"
  },
  {
    "id": "tabler:sunset",
    "label": "Zonsondergang",
    "category": "Faciliteiten",
    "keywords": "sunset"
  },
  {
    "id": "tabler:umbrella",
    "label": "Parasol",
    "category": "Faciliteiten",
    "keywords": "umbrella"
  },
  {
    "id": "tabler:grill",
    "label": "Barbecue",
    "category": "Faciliteiten",
    "keywords": "grill"
  },
  {
    "id": "tabler:tent",
    "label": "Kamperen",
    "category": "Faciliteiten",
    "keywords": "tent"
  },
  {
    "id": "tabler:campfire",
    "label": "Kampvuur",
    "category": "Faciliteiten",
    "keywords": "campfire"
  },
  {
    "id": "tabler:ball-football",
    "label": "Voetbal",
    "category": "Faciliteiten",
    "keywords": "ball football"
  },
  {
    "id": "tabler:ball-tennis",
    "label": "Tennis",
    "category": "Faciliteiten",
    "keywords": "ball tennis"
  },
  {
    "id": "tabler:device-tv",
    "label": "Televisie",
    "category": "Faciliteiten",
    "keywords": "device tv"
  },
  {
    "id": "tabler:device-laptop",
    "label": "Laptop werkplek",
    "category": "Faciliteiten",
    "keywords": "device laptop"
  },
  {
    "id": "tabler:coffee",
    "label": "Koffie ontbijt",
    "category": "Eten",
    "keywords": "coffee"
  },
  {
    "id": "tabler:cup",
    "label": "Kopje",
    "category": "Eten",
    "keywords": "cup"
  },
  {
    "id": "tabler:teapot",
    "label": "Thee",
    "category": "Eten",
    "keywords": "teapot"
  },
  {
    "id": "tabler:bread",
    "label": "Brood",
    "category": "Eten",
    "keywords": "bread"
  },
  {
    "id": "tabler:egg",
    "label": "Ei",
    "category": "Eten",
    "keywords": "egg"
  },
  {
    "id": "tabler:cheese",
    "label": "Kaas",
    "category": "Eten",
    "keywords": "cheese"
  },
  {
    "id": "tabler:milk",
    "label": "Melk",
    "category": "Eten",
    "keywords": "milk"
  },
  {
    "id": "tabler:glass",
    "label": "Glas drinken",
    "category": "Eten",
    "keywords": "glass"
  },
  {
    "id": "tabler:glass-full",
    "label": "Drankjes",
    "category": "Eten",
    "keywords": "glass full"
  },
  {
    "id": "tabler:bottle",
    "label": "Fles",
    "category": "Eten",
    "keywords": "bottle"
  },
  {
    "id": "tabler:glass-cocktail",
    "label": "Wijn cocktail",
    "category": "Eten",
    "keywords": "glass cocktail"
  },
  {
    "id": "tabler:beer",
    "label": "Bier",
    "category": "Eten",
    "keywords": "beer"
  },
  {
    "id": "tabler:tools-kitchen-2",
    "label": "Restaurant eten diner",
    "category": "Eten",
    "keywords": "tools kitchen 2"
  },
  {
    "id": "tabler:tools-kitchen",
    "label": "Keuken koken",
    "category": "Eten",
    "keywords": "tools kitchen"
  },
  {
    "id": "tabler:fridge",
    "label": "Koelkast",
    "category": "Eten",
    "keywords": "fridge"
  },
  {
    "id": "tabler:microwave",
    "label": "Magnetron",
    "category": "Eten",
    "keywords": "microwave"
  },
  {
    "id": "tabler:apple",
    "label": "Fruit",
    "category": "Eten",
    "keywords": "apple"
  },
  {
    "id": "tabler:carrot",
    "label": "Groente vegetarisch",
    "category": "Eten",
    "keywords": "carrot"
  },
  {
    "id": "tabler:fish",
    "label": "Vis",
    "category": "Eten",
    "keywords": "fish"
  },
  {
    "id": "tabler:meat",
    "label": "Vlees",
    "category": "Eten",
    "keywords": "meat"
  },
  {
    "id": "tabler:salad",
    "label": "Salade vegan",
    "category": "Eten",
    "keywords": "salad"
  },
  {
    "id": "tabler:pizza",
    "label": "Pizza",
    "category": "Eten",
    "keywords": "pizza"
  },
  {
    "id": "tabler:cake",
    "label": "Taart",
    "category": "Eten",
    "keywords": "cake"
  },
  {
    "id": "tabler:ice-cream",
    "label": "IJs",
    "category": "Eten",
    "keywords": "ice cream"
  },
  {
    "id": "tabler:cookie",
    "label": "Koekje",
    "category": "Eten",
    "keywords": "cookie"
  },
  {
    "id": "tabler:phone",
    "label": "Telefoon bellen",
    "category": "Contact",
    "keywords": "phone"
  },
  {
    "id": "tabler:phone-call",
    "label": "Telefonisch contact",
    "category": "Contact",
    "keywords": "phone call"
  },
  {
    "id": "tabler:mail",
    "label": "E-mail email post",
    "category": "Contact",
    "keywords": "mail"
  },
  {
    "id": "tabler:mail-opened",
    "label": "Bericht ontvangen",
    "category": "Contact",
    "keywords": "mail opened"
  },
  {
    "id": "tabler:map-pin",
    "label": "Adres locatie",
    "category": "Contact",
    "keywords": "map pin"
  },
  {
    "id": "tabler:map",
    "label": "Kaart",
    "category": "Contact",
    "keywords": "map"
  },
  {
    "id": "tabler:route",
    "label": "Route",
    "category": "Contact",
    "keywords": "route"
  },
  {
    "id": "tabler:navigation",
    "label": "Navigatie",
    "category": "Contact",
    "keywords": "navigation"
  },
  {
    "id": "tabler:compass",
    "label": "Kompas",
    "category": "Contact",
    "keywords": "compass"
  },
  {
    "id": "tabler:world",
    "label": "Website wereld",
    "category": "Contact",
    "keywords": "world"
  },
  {
    "id": "tabler:message",
    "label": "Bericht",
    "category": "Contact",
    "keywords": "message"
  },
  {
    "id": "tabler:messages",
    "label": "Gesprek chat",
    "category": "Contact",
    "keywords": "messages"
  },
  {
    "id": "tabler:send",
    "label": "Versturen",
    "category": "Contact",
    "keywords": "send"
  },
  {
    "id": "tabler:at",
    "label": "E-mailadres",
    "category": "Contact",
    "keywords": "at"
  },
  {
    "id": "tabler:address-book",
    "label": "Adresboek",
    "category": "Contact",
    "keywords": "address book"
  },
  {
    "id": "tabler:headphones",
    "label": "Ondersteuning support",
    "category": "Contact",
    "keywords": "headphones"
  },
  {
    "id": "tabler:headset",
    "label": "Klantenservice",
    "category": "Contact",
    "keywords": "headset"
  },
  {
    "id": "tabler:clock",
    "label": "Tijd openingstijden",
    "category": "Contact",
    "keywords": "clock"
  },
  {
    "id": "tabler:calendar",
    "label": "Kalender datum",
    "category": "Contact",
    "keywords": "calendar"
  },
  {
    "id": "tabler:calendar-event",
    "label": "Afspraak reservering",
    "category": "Contact",
    "keywords": "calendar event"
  },
  {
    "id": "tabler:arrow-right",
    "label": "Pijl naar rechts",
    "category": "Algemeen",
    "keywords": "arrow right"
  },
  {
    "id": "tabler:check",
    "label": "Vinkje inbegrepen",
    "category": "Algemeen",
    "keywords": "check"
  },
  {
    "id": "tabler:checks",
    "label": "Dubbel vinkje",
    "category": "Algemeen",
    "keywords": "checks"
  },
  {
    "id": "tabler:circle-check",
    "label": "Goedgekeurd",
    "category": "Algemeen",
    "keywords": "circle check"
  },
  {
    "id": "tabler:x",
    "label": "Kruis niet inbegrepen",
    "category": "Algemeen",
    "keywords": "x"
  },
  {
    "id": "tabler:plus",
    "label": "Toevoegen",
    "category": "Algemeen",
    "keywords": "plus"
  },
  {
    "id": "tabler:minus",
    "label": "Minteken",
    "category": "Algemeen",
    "keywords": "minus"
  },
  {
    "id": "tabler:star",
    "label": "Ster favoriet",
    "category": "Algemeen",
    "keywords": "star"
  },
  {
    "id": "tabler:heart",
    "label": "Hart liefde",
    "category": "Algemeen",
    "keywords": "heart"
  },
  {
    "id": "tabler:thumb-up",
    "label": "Aanbevolen",
    "category": "Algemeen",
    "keywords": "thumb up"
  },
  {
    "id": "tabler:award",
    "label": "Onderscheiding",
    "category": "Algemeen",
    "keywords": "award"
  },
  {
    "id": "tabler:trophy",
    "label": "Trofee",
    "category": "Algemeen",
    "keywords": "trophy"
  },
  {
    "id": "tabler:certificate",
    "label": "Certificaat",
    "category": "Algemeen",
    "keywords": "certificate"
  },
  {
    "id": "tabler:shield-check",
    "label": "Veilig betrouwbaar",
    "category": "Algemeen",
    "keywords": "shield check"
  },
  {
    "id": "tabler:rosette-discount-check",
    "label": "Geverifieerd",
    "category": "Algemeen",
    "keywords": "rosette discount check"
  },
  {
    "id": "tabler:sparkles",
    "label": "Bijzonder luxe",
    "category": "Algemeen",
    "keywords": "sparkles"
  },
  {
    "id": "tabler:bolt",
    "label": "Snel energie",
    "category": "Algemeen",
    "keywords": "bolt"
  },
  {
    "id": "tabler:gift",
    "label": "Cadeau gratis",
    "category": "Algemeen",
    "keywords": "gift"
  },
  {
    "id": "tabler:discount",
    "label": "Korting",
    "category": "Algemeen",
    "keywords": "discount"
  },
  {
    "id": "tabler:tag",
    "label": "Label",
    "category": "Algemeen",
    "keywords": "tag"
  },
  {
    "id": "tabler:currency-euro",
    "label": "Euro prijs",
    "category": "Algemeen",
    "keywords": "currency euro"
  },
  {
    "id": "tabler:credit-card",
    "label": "Betalen",
    "category": "Algemeen",
    "keywords": "credit card"
  },
  {
    "id": "tabler:cash",
    "label": "Contant",
    "category": "Algemeen",
    "keywords": "cash"
  },
  {
    "id": "tabler:wallet",
    "label": "Portemonnee",
    "category": "Algemeen",
    "keywords": "wallet"
  },
  {
    "id": "tabler:receipt",
    "label": "Bon factuur",
    "category": "Algemeen",
    "keywords": "receipt"
  },
  {
    "id": "tabler:shopping-bag",
    "label": "Winkelen",
    "category": "Algemeen",
    "keywords": "shopping bag"
  },
  {
    "id": "tabler:user",
    "label": "Persoon",
    "category": "Algemeen",
    "keywords": "user"
  },
  {
    "id": "tabler:users",
    "label": "Groep gezin",
    "category": "Algemeen",
    "keywords": "users"
  },
  {
    "id": "tabler:user-check",
    "label": "Persoonlijke service",
    "category": "Algemeen",
    "keywords": "user check"
  },
  {
    "id": "tabler:briefcase",
    "label": "Zakelijk",
    "category": "Algemeen",
    "keywords": "briefcase"
  },
  {
    "id": "tabler:tools",
    "label": "Gereedschap vakmanschap",
    "category": "Algemeen",
    "keywords": "tools"
  },
  {
    "id": "tabler:settings",
    "label": "Instellingen",
    "category": "Algemeen",
    "keywords": "settings"
  },
  {
    "id": "tabler:info-circle",
    "label": "Informatie",
    "category": "Algemeen",
    "keywords": "info circle"
  },
  {
    "id": "tabler:help",
    "label": "Hulp",
    "category": "Algemeen",
    "keywords": "help"
  },
  {
    "id": "tabler:bulb",
    "label": "Idee advies",
    "category": "Algemeen",
    "keywords": "bulb"
  },
  {
    "id": "tabler:book",
    "label": "Boek lezen",
    "category": "Algemeen",
    "keywords": "book"
  }
] as const
