/**
 * Color Palettes
 * Professional color combinations for business websites
 */

import type { ThemePalette } from './types';

export const COLOR_PALETTES: ThemePalette[] = [
  // Modern & Professional
  {
    id: 'slate-modern',
    name: 'Slate Modern',
    colors: {
      primary: '#1e293b',
      primaryForeground: '#f8fafc',
      secondary: '#64748b',
      secondaryForeground: '#f8fafc',
      accent: '#3b82f6',
      accentForeground: '#ffffff',
      background: '#ffffff',
      foreground: '#0f172a',
      muted: '#f1f5f9',
      mutedForeground: '#64748b',
      card: '#ffffff',
      cardForeground: '#0f172a',
      border: '#e2e8f0',
    },
  },
  {
    id: 'ocean-blue',
    name: 'Ocean Blue',
    colors: {
      primary: '#0369a1',
      primaryForeground: '#ffffff',
      secondary: '#0ea5e9',
      secondaryForeground: '#ffffff',
      accent: '#06b6d4',
      accentForeground: '#ffffff',
      background: '#f0f9ff',
      foreground: '#0c4a6e',
      muted: '#e0f2fe',
      mutedForeground: '#0369a1',
      card: '#ffffff',
      cardForeground: '#0c4a6e',
      border: '#bae6fd',
    },
  },
  {
    id: 'forest-green',
    name: 'Forest Green',
    colors: {
      primary: '#166534',
      primaryForeground: '#ffffff',
      secondary: '#22c55e',
      secondaryForeground: '#ffffff',
      accent: '#84cc16',
      accentForeground: '#1a2e05',
      background: '#f0fdf4',
      foreground: '#14532d',
      muted: '#dcfce7',
      mutedForeground: '#166534',
      card: '#ffffff',
      cardForeground: '#14532d',
      border: '#bbf7d0',
    },
  },
  {
    id: 'warm-earth',
    name: 'Warm Earth',
    colors: {
      primary: '#92400e',
      primaryForeground: '#ffffff',
      secondary: '#d97706',
      secondaryForeground: '#ffffff',
      accent: '#f59e0b',
      accentForeground: '#451a03',
      background: '#fffbeb',
      foreground: '#78350f',
      muted: '#fef3c7',
      mutedForeground: '#92400e',
      card: '#ffffff',
      cardForeground: '#78350f',
      border: '#fde68a',
    },
  },
  {
    id: 'rose-elegant',
    name: 'Rose Elegant',
    colors: {
      primary: '#9f1239',
      primaryForeground: '#ffffff',
      secondary: '#e11d48',
      secondaryForeground: '#ffffff',
      accent: '#fb7185',
      accentForeground: '#4c0519',
      background: '#fff1f2',
      foreground: '#881337',
      muted: '#ffe4e6',
      mutedForeground: '#9f1239',
      card: '#ffffff',
      cardForeground: '#881337',
      border: '#fecdd3',
    },
  },
  // Dark Themes
  {
    id: 'midnight',
    name: 'Midnight',
    colors: {
      primary: '#818cf8',
      primaryForeground: '#1e1b4b',
      secondary: '#6366f1',
      secondaryForeground: '#ffffff',
      accent: '#a5b4fc',
      accentForeground: '#1e1b4b',
      background: '#0f0f23',
      foreground: '#e2e8f0',
      muted: '#1e1b4b',
      mutedForeground: '#a5b4fc',
      card: '#1a1a2e',
      cardForeground: '#e2e8f0',
      border: '#312e81',
    },
  },
  {
    id: 'charcoal',
    name: 'Charcoal',
    colors: {
      primary: '#f8fafc',
      primaryForeground: '#0f172a',
      secondary: '#94a3b8',
      secondaryForeground: '#0f172a',
      accent: '#38bdf8',
      accentForeground: '#0c4a6e',
      background: '#0f172a',
      foreground: '#f1f5f9',
      muted: '#1e293b',
      mutedForeground: '#94a3b8',
      card: '#1e293b',
      cardForeground: '#f1f5f9',
      border: '#334155',
    },
  },
  // Warm & Inviting
  {
    id: 'terracotta',
    name: 'Terracotta',
    colors: {
      primary: '#c2410c',
      primaryForeground: '#ffffff',
      secondary: '#ea580c',
      secondaryForeground: '#ffffff',
      accent: '#fb923c',
      accentForeground: '#431407',
      background: '#fef7ed',
      foreground: '#7c2d12',
      muted: '#fed7aa',
      mutedForeground: '#9a3412',
      card: '#ffffff',
      cardForeground: '#7c2d12',
      border: '#fdba74',
    },
  },
  {
    id: 'burgundy',
    name: 'Burgundy',
    colors: {
      primary: '#7f1d1d',
      primaryForeground: '#ffffff',
      secondary: '#b91c1c',
      secondaryForeground: '#ffffff',
      accent: '#dc2626',
      accentForeground: '#ffffff',
      background: '#fef2f2',
      foreground: '#450a0a',
      muted: '#fee2e2',
      mutedForeground: '#7f1d1d',
      card: '#ffffff',
      cardForeground: '#450a0a',
      border: '#fecaca',
    },
  },
  // Cool & Professional
  {
    id: 'steel-blue',
    name: 'Steel Blue',
    colors: {
      primary: '#1e40af',
      primaryForeground: '#ffffff',
      secondary: '#3b82f6',
      secondaryForeground: '#ffffff',
      accent: '#60a5fa',
      accentForeground: '#1e3a8a',
      background: '#eff6ff',
      foreground: '#1e3a8a',
      muted: '#dbeafe',
      mutedForeground: '#1e40af',
      card: '#ffffff',
      cardForeground: '#1e3a8a',
      border: '#bfdbfe',
    },
  },
  {
    id: 'teal-fresh',
    name: 'Teal Fresh',
    colors: {
      primary: '#0f766e',
      primaryForeground: '#ffffff',
      secondary: '#14b8a6',
      secondaryForeground: '#ffffff',
      accent: '#2dd4bf',
      accentForeground: '#134e4a',
      background: '#f0fdfa',
      foreground: '#134e4a',
      muted: '#ccfbf1',
      mutedForeground: '#0f766e',
      card: '#ffffff',
      cardForeground: '#134e4a',
      border: '#99f6e4',
    },
  },
  // Neutral & Minimal
  {
    id: 'pure-minimal',
    name: 'Pure Minimal',
    colors: {
      primary: '#171717',
      primaryForeground: '#fafafa',
      secondary: '#525252',
      secondaryForeground: '#fafafa',
      accent: '#737373',
      accentForeground: '#fafafa',
      background: '#fafafa',
      foreground: '#171717',
      muted: '#f5f5f5',
      mutedForeground: '#525252',
      card: '#ffffff',
      cardForeground: '#171717',
      border: '#e5e5e5',
    },
  },
  {
    id: 'warm-neutral',
    name: 'Warm Neutral',
    colors: {
      primary: '#44403c',
      primaryForeground: '#fafaf9',
      secondary: '#78716c',
      secondaryForeground: '#fafaf9',
      accent: '#a8a29e',
      accentForeground: '#1c1917',
      background: '#fafaf9',
      foreground: '#1c1917',
      muted: '#f5f5f4',
      mutedForeground: '#57534e',
      card: '#ffffff',
      cardForeground: '#1c1917',
      border: '#e7e5e4',
    },
  },
  // Bold & Creative
  {
    id: 'electric',
    name: 'Electric',
    colors: {
      primary: '#7c3aed',
      primaryForeground: '#ffffff',
      secondary: '#8b5cf6',
      secondaryForeground: '#ffffff',
      accent: '#f472b6',
      accentForeground: '#831843',
      background: '#faf5ff',
      foreground: '#4c1d95',
      muted: '#f3e8ff',
      mutedForeground: '#6d28d9',
      card: '#ffffff',
      cardForeground: '#4c1d95',
      border: '#e9d5ff',
    },
  },
  {
    id: 'sunset',
    name: 'Sunset',
    colors: {
      primary: '#dc2626',
      primaryForeground: '#ffffff',
      secondary: '#f97316',
      secondaryForeground: '#ffffff',
      accent: '#fbbf24',
      accentForeground: '#78350f',
      background: '#fffbeb',
      foreground: '#7c2d12',
      muted: '#fef3c7',
      mutedForeground: '#b45309',
      card: '#ffffff',
      cardForeground: '#7c2d12',
      border: '#fde68a',
    },
  },
];

// Helper to get palette by ID
export function getPaletteById(id: string): ThemePalette | undefined {
  return COLOR_PALETTES.find((p) => p.id === id);
}

// Default palette
export const DEFAULT_PALETTE_ID = 'slate-modern';
