begin;

alter table public.websites
  add column if not exists applied_template_id text;

update public.websites as website
set applied_template_id = case business.category
  when 'bnb' then 'bnb-hospitality'
  when 'hairdresser' then 'hairdresser-luxury'
  when 'gardener' then 'gardener-nature'
  when 'coach' then 'coach-wellness'
  when 'restaurant' then 'restaurant-dining'
  when 'photographer' then 'photographer-portfolio'
  when 'freelancer' then 'freelancer-professional'
  when 'construction' then 'construction-build'
  when 'general_service' then 'general-service-default'
  else null
end
from public.businesses as business
where website.business_id = business.id
  and website.applied_template_id is null;

comment on column public.websites.applied_template_id is
  'Last template applied to this website; used for aggregate product analytics.';

create table if not exists public.website_visits (
  id bigint generated by default as identity primary key,
  website_id uuid not null references public.websites(id) on delete cascade,
  visited_at timestamptz not null default now()
);

create index if not exists website_visits_website_visited_at_idx
  on public.website_visits (website_id, visited_at desc);

create index if not exists website_visits_visited_at_idx
  on public.website_visits (visited_at desc);

alter table public.website_visits enable row level security;

comment on table public.website_visits is
  'Privacy-friendly public website session counts. Stores no IP address, user agent, or visitor identifier.';

commit;
